"""initial tables

Revision ID: c19bf15c3f70
Revises: 05cc403a6e5a
Create Date: 2026-04-10 20:49:40.515955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c19bf15c3f70'
down_revision: Union[str, Sequence[str], None] = '05cc403a6e5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userId', sa.Uuid(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('passwordHash', sa.String(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=False),
    sa.Column('patronymic', sa.String(), nullable=True),
    sa.Column('dateOfBirth', sa.Date(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('telegram', sa.String(), nullable=True),
    sa.Column('telegramChatId', sa.String(), nullable=True),
    sa.Column('isSeller', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('telegram'),
    sa.UniqueConstraint('telegramChatId')
    )
    op.create_index(op.f('ix_users_isSeller'), 'users', ['isSeller'], unique=False)
    op.create_table('cart',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('userId', sa.Uuid(), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('orders',
    sa.Column('orderId', sa.Uuid(), nullable=False),
    sa.Column('userId', sa.Uuid(), nullable=False),
    sa.Column('totalPrice', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('deliveryAddress', sa.String(), nullable=False),
    sa.Column('deliveryCity', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('deliveryComment', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('orderId'),
    sa.UniqueConstraint('orderId', 'userId', name='unique_order_user')
    )
    op.create_table('user_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('userId', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expiresAt', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_tokens_token'), 'user_tokens', ['token'], unique=True)
    op.create_table('cartItems',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cartId', sa.Uuid(), nullable=False),
    sa.Column('productId', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['cartId'], ['cart.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_markets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('orderId', sa.Uuid(), nullable=False),
    sa.Column('marketId', sa.UUID(), nullable=False),
    sa.Column('totalPrice', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['orderId'], ['orders.orderId'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orderId', 'marketId', name='unique_order_market')
    )
    op.create_table('OrderItems',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('orderId', sa.Uuid(), nullable=False),
    sa.Column('orderMarketId', sa.Uuid(), nullable=False),
    sa.Column('productId', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('priceAtPurchase', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['orderId'], ['orders.orderId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['orderMarketId'], ['order_markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OrderItems')
    op.drop_table('order_markets')
    op.drop_table('cartItems')
    op.drop_index(op.f('ix_user_tokens_token'), table_name='user_tokens')
    op.drop_table('user_tokens')
    op.drop_table('orders')
    op.drop_table('cart')
    op.drop_index(op.f('ix_users_isSeller'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
